### PR TITLE
Remove Eden relay

### PR DESCRIPTION
**Pull request by yorickdowne**

### CODE REVIEW

**Comment by pietjepuk2** [comment]
Because it's broken, doesn't exist anymore, they're lying/cheating...? Otherwise LGTM

**Comment by yorickdowne** [comment]
Because it doesn't exist any more. 

https://x.com/titanrelayxyz/status/1829202005354807374

**Comment by pietjepuk2** [comment]
Ahh, OK. And I see that titan relay is not part of the mainnet list (yet)?

**Comment by yorickdowne** [comment]
Yeah, Titan was still new when that list was last touched. I can certainly do a second PR to add Titan to mainnet: I think they've proven themselves.

**Review by pietjepuk2 — APPROVED** [review]

**Pull request merged**
