### PR TITLE
Add ETH Docker Logs dashboard

### PR DESCRIPTION
**Pull request by gorillamania**
Adds a new dashboard to Grafana that allows for people to view their Execution, Consensys, Validator, and MEV-boost logs, searchable by time and viewed on one page. 

Also adds loki logging to the mev-boost container, so we can show logs for it too.

https://grafana.com/grafana/dashboards/18700-eth-docker-logs/

Screenshot 2023-05-12 at 11 14 03 PM

Ref: https://github.com/eth-educators/eth-docker/issues/1381

### CODE REVIEW

**Comment by gorillamania** [comment]
I tested this with a clean install btw.

**Comment by yorickdowne** [comment]
Looks great, thank you!

**Comment by nflaig** [comment]
This is awesome! Required some manual effort to make it work on my end since my containers are not prefixed with `eth-docker` due to different `COMPOSE_PROJECT_NAME` / folder name.

**Comment by yorickdowne** [comment]
Can you think of a way to make this dashboard independent of the project name?

**Comment by gorillamania** [comment]
We could probably change the filtering to be a regex instead of a hard coded container name

@nflaig - can you provide more detail on what changes you had to make?

**Comment by nflaig** [comment]
@gorillamania it is pretty simple, just updating the container name in label filters

image

**Pull request merged**
