### PR TITLE
Fixed broken interpolation

### PR DESCRIPTION
**Pull request by currentoor**
Was getting the following error when trying to update.

`ERROR: Invalid interpolation format for "environment" option in service "consensus": "RAPID_SYNC_URL=${RAPID_SYNC_URL:-}"`

### CODE REVIEW

**Comment by yorickdowne** [comment]
Odd. Let me see what's going on.

**Comment by yorickdowne** [comment]
I am not seeing the issue you are seeing. Can you show me a `docker-compose --version` and `docker --version`? This is written that way for a reason, to avoid errors when `RAPID_SYNC_URL` is not in `.env`

I am wondering what's different between my environment and yours.

**Comment by yorickdowne** [comment]
Should be fixed with #559 . Thank you for the report!

**Comment by yorickdowne** [comment]
Hey help me out here if you would. I had to bring this back for KEYSTORE_PASSWORD since that's only sent in shell environment, not .env, and would show errors otherwise. On my docker-compose at least `${VAR:-}` is valid and becomes an empty string once it's through `docker-compose config`. 

Tell me about your environment please. OS, docker distribution chosen (io? CE? Desktop? Something else?), and relevant versions for everything.

**Comment by currentoor** [comment]
@yorickdowne sure, I'm running on 

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"

$ docker -v
Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3
```

m5.xlarge EC2 instance in AWS.

Is there anything else you need?

**Comment by yorickdowne** [comment]
Interesting. Can you test this again on 20.04 or 22.04 please? Zero testing was done on 18.04 since that’s “ancient”, tm.

**Comment by yorickdowne** [comment]
No worries at all! I'm glad this got sorted out, and it's a good data point to have. Arguably ethd could check for Ubuntu version and warn if < 20.04

**Pull request closed without merging**
