### PR TITLE
Add build image step to MERGE-READY.md

### PR DESCRIPTION
**Pull request by jimmygchen**

### CODE REVIEW

**Comment by yorickdowne** [comment]
Hmm I don't think this is necessary, as `./ethd config` already has a build step at the end of it.

What scenario do you have in mind? Building after manually changing things in `.env`?

**Comment by jimmygchen** [comment]
Oh really, that's strange. I was basically just following the steps, i.e. ran `./ethd config` first, generated keys and then when I run `./ethd keyimport`, it was unable to find the `teku:merge` image. I don't think I've changed anything manually in `.env`.

But I can try again later to see if I can reproduce this.

**Comment by yorickdowne** [comment]
After `./ethd config`:

```
Successfully built a11b872223e1
Successfully tagged teku:merge
```

Is it possible you configured a CL other than Teku, changed it in `.env` to Teku, and then tried to import? In that case yes, a manual build step is required.

**Comment by jimmygchen** [comment]
So I managed to reproduce on another machine - is it because I'm not running key generation?


```
➜  eth-docker git:(merge-getready) ./ethd config
Your configuration file template is: default.env
You chose to run on goerli testnet
Your deployment choice is: node
Your consensus client file is: teku-base.yml
Your execution client file is: geth.yml
Your rewards address is:
your Graffiti is: 🐼eth-docker🐼
Your COMPOSE_FILE is: teku-base.yml:geth.yml:deposit-cli.yml
➜  eth-docker git:(merge-getready) ./ethd
➜  eth-docker git:(merge-getready) ./ethd ./ethd keyimport
➜  eth-docker git:(merge-getready) ./ethd keyimport
Creating network "eth-docker_default" with the default driver
Creating volume "eth-docker_teku-data" with default driver
Creating volume "eth-docker_jwtsecret" with default driver
Creating volume "eth-docker_geth-eth1-data" with default driver
Pulling validator-import (teku:merge)...
ERROR: pull access denied for teku, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by jimmygchen** [comment]
> After `./ethd config`:
> 
> ```
> Successfully built a11b872223e1
> Successfully tagged teku:merge
> ```
> 
> Is it possible you configured a CL other than Teku, changed it in `.env` to Teku, and then tried to import? In that case yes, a manual build step is required.

No, I selected Teku in the wizard and didn't change afterwards

**Comment by jimmygchen** [comment]
I realise there isn't enough info for you to debug - I'll provide more details on the inputs I used in the wizard shortly

**Comment by jimmygchen** [comment]
ah it's probably something to do with my user config - just found this conditional in `ethd`:

```
    if [[ "${EUID}" -eq 0 || -n $(id -nG $(id -u) | grep -w "docker") ]]; then
        cmd build --pull
...
```
 
So my user is not part of the docker group. My bad didn't read instructions properly, thought this was optional :) Just realised it's in the prerequisites for Linux but not macOS - docker works in macOS without adding user to the group but pull with `ethd config`.

**Comment by yorickdowne** [comment]
You always have the option of running with `sudo` so there's docker access, as in `sudo ./ethd config`, or you can of course do the build manually after.

**Comment by yorickdowne** [comment]
I don't have a Mac so I can't really test how this works there, and what the best way is to make sure docker works

**Comment by jimmygchen** [comment]
> You always have the option of running with `sudo` so there's docker access, as in `sudo ./ethd config`, or you can of course do the build manually after.

Yep, I'm doing `sudo` for docker commands - so yeah, the build step is not necessary for users that already have user added to the docker group. Happy to close this one, thanks!

ps. For macOS (with Docker Desktop) - docker works for me without sudo / adding user to the docker group, so I just needed to run the build manually after `ethd config`

**Comment by yorickdowne** [comment]
Could you `./ethd update` and see whether it now builds. I added an "or if macOS"

**Comment by jimmygchen** [comment]
Hey @yorickdowne yes it does build now after `eth update`, thanks!

However I got quite a few of these but I haven't noticed any impact, looks like Mac doesn't support the `-P` option:

```
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

**Comment by yorickdowne** [comment]
Hmmm ....

**Comment by yorickdowne** [comment]
Do me a solid and try again, please. I've replaced all those `grep` with `sed` for better macOS compatibility. And thanks for being my macOS tester!

**Comment by jimmygchen** [comment]
Hi @yorickdowne I can confirm that both `./ethd config` and `./ethd update` now runs the build step without errors on my Mac now. Thank you for this!

**Pull request closed without merging**
